name: Documentation build

on:
  push:
    branches: [dev,main]
  pull_request:
    branches: [dev,main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: documentation_html
        path: docs/_build/html/
